const projects = [
  {
    id: "PJ101",
    title: "FoodMate",
    desc: "AI-powered Recipe Recommendation App",
    category: "Application Development",
  },
  {
    id: "PJ102",
    title: "TravelEase",
    desc: "Smart Trip Planner with Budget Optimization",
    category: "Mobile App",
  },
  {
    id: "PJ103",
    title: "SkillForge",
    desc: "Peer-to-Peer Online Skill Sharing Platform",
    category: "Website Development",
  },
  {
    id: "PJ104",
    title: "FarmFresh",
    desc: "Organic Food Delivery from Local Farmers",
    category: "E-Commerce",
  },
  {
    id: "PJ105",
    title: "MediTrack",
    desc: "Health Monitoring and Medicine Reminder App",
    category: "Healthcare",
  },
  {
    id: "PJ106",
    title: "EventHub",
    desc: "Smart Event Ticket Booking and Management",
    category: "Application Development",
  },
  {
    id: "PJ107",
    title: "GreenSteps",
    desc: "Carbon Footprint Tracker for Individuals",
    category: "Mobile App",
  },
  {
    id: "PJ108",
    title: "StudyBuddy",
    desc: "Collaborative Learning Platform for Students",
    category: "Website Development",
  },
  {
    id: "PJ109",
    title: "WorkNest",
    desc: "Remote Work Collaboration & Productivity Tool",
    category: "Application Development",
  },
  {
    id: "PJ110",
    title: "ShopLink",
    desc: "Unified Online Shopping Price Comparison Tool",
    category: "E-Commerce",
  },
  {
    id: "PJ111",
    title: "PetCare",
    desc: "Smart Pet Health and Tracking Application",
    category: "Healthcare",
  },
  {
    id: "PJ112",
    title: "CityConnect",
    desc: "Digital Complaint & Suggestion Board for Cities",
    category: "Website Development",
  },
  {
    id: "PJ113",
    title: "TaskFlow",
    desc: "AI-powered To-do & Task Automation Tool",
    category: "Application Development",
  },
  {
    id: "PJ114",
    title: "GameZone",
    desc: "Online Multiplayer Mini-Games Platform",
    category: "Mobile App",
  },
  {
    id: "PJ115",
    title: "DocuSafe",
    desc: "Secure Cloud Document Storage and Sharing",
    category: "Website Development",
  },
  {
    id: "PJ116",
    title: "RideNow",
    desc: "Smart Carpool & Ride-Sharing Application",
    category: "Application Development",
  },
  {
    id: "PJ117",
    title: "BudgetPal",
    desc: "AI Expense Tracker and Budget Planner",
    category: "Mobile App",
  },
  {
    id: "PJ118",
    title: "NewsSphere",
    desc: "Personalized News Aggregator Website",
    category: "Website Development",
  },
  {
    id: "PJ119",
    title: "ShopSmart",
    desc: "Smart Grocery Shopping with Auto Suggestions",
    category: "E-Commerce",
  },
  {
    id: "PJ120",
    title: "CareBridge",
    desc: "Virtual Doctor Consultation and Reports App",
    category: "Healthcare",
  },
];
